### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by codeyash** [fro0m/qt-rest-client#1]
Please don't remove my name from copyright of this.

https://github.com/fro0m/qt-rest-client/blob/master/HttpRequestWorker.cpp and
https://github.com/fro0m/qt-rest-client/blob/master/HttpRequestWorker.h

You may add more names.

Thanks

**Comment by fro0m** [comment]
​hi, whatactions should I make to add author names?​

**Comment by codeyash** [comment]
Thanks for adding.
